language: generic

branches:
  only:
  - master

jobs:
  include:
    - os: linux
      dist: xenial
      sudo: false
      script:
        - ./bin/update_dotfiles.sh
        - source ~/.bashrc
    - os: osx
      script:
        - ./bin/update_dotfiles.sh
        - source ~/.bashrc
    - os: windows
      script:
        - ./bin/update_dotfiles.sh
        - source ~/.bashrc



