language: generic

branches:
  only:
  - main

jobs:
  include:
    - os: linux
      dist: bionic
      sudo: false
      script:
        - ./bin/update_dotfiles.sh
        - source ~/.bashrc
    - os: osx
      osx_image: xcode12.2
      script:
        - ./bin/update_dotfiles.sh
        - source ~/.bashrc
