language: generic

branches:
  only:
  - master

stages:
  - name: linux
  - name: osx

jobs:
  include:
    - stage: linux
      os: linux
      dist: xenial
      sudo: false
    - stage: osx
      os: osx

script:
  - ./bin/update_dotfiles.sh
  - source ~/.bashrc
